* Emacs Conference 2015?

Let's make it happen! Contribute to this repository at
https://github.com/sachac/emacsconf2015, or e-mail me at
[[mailto:sacha@sachachua.com][sacha@sachachua.com]] . Web version: http://sachac.github.io/emacsconf2015

Event: https://plus.google.com/events/cgd1kva6f473osvgvq6biuinhn4

** Ideas for sessions
*** The State of Emacs

The kernel of this idea is basically to have a "State of the Union" address, where the Union is Emacs. I think it would be awesome if someone really embedded in Emacs development (specifically thinking of Stefan) talked about the current state of Emacs development with regards to
- how development today is functioning. What are major development process problems that need to be fixed but haven't? What do the maintainers of Emacs stress about (letting patches rot in debbugs, having bugs rot in debbugs, being unsure of the general brokenness of Emacs because of the lack of testing), and what processes can be put in place to ease their anxieties?
- new contributors. Making Emacs easier for new contributors was a *huge* topic in the Fall of 2014 on emacs-devel. The switch to git was seen as the first step, what were the next steps and how did they work?
- whether anything surprisingly good/bad has happened this year.
- the general state of emacs-devel.
- and what we can do to help! :D
(suggested by Samer)

*** What's new in Emacs 25?
**** What's new for users?
**** What's new for developers?
*** Updates on interesting things
**** Guile Emacs
   I think it would be awesome if Robin Templeton or BT Templeton (there is a chance that they're the same person, I'm still not clear on that...) talked about the state of Guile Emacs.
   - What works? What's left to be done?
   - What does Guile replace in the core Emacs engine?
   - *Is Guile Emacs the future of Emacs?* Is Guile Emacs going to *happen* and be merged into trunk at some point in the future? If so, what's needed to get us there, otherwise, why not?
   And what can we do to help! :D :D

Suggested by Samer

*** What are some interesting uses of Emacs?
**** Reproducible research
- How do you manage your literature review?
- How do you analyze your data?
- How do you work with charts and graphs?
- How can you publish in the required formats?
- What have your experiences been like using this? Advantages? Gaps?
*** What are good workflows for common needs?
**** Programming
- C/C++
- Rails
- Javascript
- Java
- Clojure
- Scala
- Python

**** Writing and research
- Reproducible research
- Writing prose
- Org for publishing
- Knowledge management
*** How can people contribute to Emacs core?
Walkthrough of how to:
- find a small bug to work on
- navigate the source code
- prepare a patch
- work with emacs-devel
*** How can packaging get even better?
Nic Ferrier? Steve Purcell? Milkypostman?
*** What can we build with interesting capabilities available in Emacs? How?
- httpd, elnode; skewer, impatient - @skeeto?
- comint, NREPL

*** Design and Evolution of [[https://github.com/syl20bnr/spacemacs/][Spacemacs]] by @syl20bnr

- Why evil + spacebar
- Why guide-key
- Why layers
- Vim concepts being brought over - Vundle, etc.
- State of evil - what is not ideal yet? what are missing features from the ecosystem?
- How can contributors help?

*** What can improve the usability of Emacs?
Concrete tips, demonstrations

- tutorials
- discoverability
- command mode / god-mode / composable commands
- Hydra

People: Xah Lee? bbatsov? Steve Purcell? abo-abo?

*** What are good development practices for Emacs Lisp?
- Automated testing
- Continuous integration and testing on multiple Emacsen
- Code coverage reporting
- Emacs Lisp style and package linting
- Refactoring
- Performance
**** Useful utilities
Maybe with before/after code?

- s.el
- f.el
- dash.el
- writing asynchronous code

*** How can we get more people from beginner to intermediate?
*** How can we get more people to begin using Emacs and stick with it for a while?
- How can interactive tutorials do a better job of introducing and selling Emacs? - Phillip Lord?

*** Organizing Emacs meetups
**** Identifying people by area who might be interested in an Emacs meetup
- San Francisco: Samer

*** Lightning talks: Workflow tips and favourite packages
- Magit
- Ebib
- EWW
- ESS
*** Hackathons and workshops
**** How can you create a package and submit it to the Emacs package repositories?
**** How can you build better interactive tutorials?
- Phillip Lord?

*** ...

** Tasks
*** TODO Collect ideas for sessions

What makes a good session?
- Something that's great as a demonstration instead of a blog post with screenshots
- Something that people have lots of questions about
- Something that benefits from multiple perspectives (like a panel)
*** TODO Set up some kind of mailing list for announcements
*** TODO Decide on a date
August, maybe a Saturday?
*** TODO Find speakers
*** TODO Set up schedule
*** TODO Facilitate sessions and questions


* Comments

Contribute to this repository at
https://github.com/sachac/emacsconf2015, or e-mail me at
[[mailto:sacha@sachachua.com][sacha@sachachua.com]] . Looking forward to hearing from you!

* Thanks

- Phillip Lord, Phil Hudson, Samer Masterson, ...
